<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net4.0</TargetFramework>
        <RootNamespace>harlowe_parser</RootNamespace>
        <AssemblyName>harlowe_parser</AssemblyName>
        <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="HtmlAgilityPack" Version="1.11.46" />
    </ItemGroup>
</Project>
