using System.Collections.Generic;
using Harlowe.Runtime;
using Xunit;

namespace Harlowe.Tests.Runtime
{
  public class MulberryRngTests
  {
    // Reference vectors: seed -> first 10 mulberry32 draws at iter 0. Generated by
    // running reference Harlowe's ts/state/prng.ts (mulberryMurmur32) verbatim
    // under Node — independent of this C# port, so they verify byte-for-byte
    // compatibility, not just internal self-consistency. Regenerate with:
    //
    //   const {imul} = Math
    //   function m(s, iter=0){ let k,i=0,h=2166136261
    //     for(;i<s.length;i+=1){k=imul(s.charCodeAt(i),3432918353);k=k<<15|k>>>17
    //       h^=imul(k,461845907);h=h<<13|h>>>19;h=imul(h,5)+3864292196|0}
    //     h^=s.length;h^=h>>>16;h=imul(h,2246822507);h^=h>>>13
    //     h=imul(h,3266489909);h^=h>>>16;h=(h>>>0)+0x6D2B79F5*iter
    //     return()=>{let t=h+=0x6D2B79F5;t=imul(t^t>>>15,t|1)
    //       t^=t+imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
    //
    public static IEnumerable<object[]> ReferenceVectors()
    {
      yield return Vec("", 0.42607066384516656, 0.8997582762967795, 0.001342930132523179, 0.6604374493472278, 0.1625607176683843, 0.2564839730039239, 0.8823842832352966, 0.6055954762268811, 0.08037240407429636, 0.12057254556566477);
      yield return Vec("0", 0.21951588313095272, 0.7236631435807794, 0.5250166414771229, 0.38337973575107753, 0.6209542497526854, 0.3010977804660797, 0.0036775467451661825, 0.7447257558815181, 0.3622421792242676, 0.523514874279499);
      yield return Vec("1", 0.3161316884215921, 0.3335980761330575, 0.5352850437629968, 0.8999942124355584, 0.43326225387863815, 0.7905533814337105, 0.5092547964304686, 0.5493843152653426, 0.11838321946561337, 0.8530461208429188);
      yield return Vec("42", 0.586788424057886, 0.8392360175494105, 0.7137607175391167, 0.4549242511857301, 0.7965460876002908, 0.7285564804915339, 0.08414380415342748, 0.18567983293905854, 0.9333906394895166, 0.511142682749778);
      yield return Vec("123", 0.439440289279446, 0.6268507752101868, 0.28362805279903114, 0.13403980480507016, 0.07069512736052275, 0.3111167794559151, 0.6183909685350955, 0.1616908865980804, 0.10084160510450602, 0.20438916329294443);
      yield return Vec("abc", 0.3132627196609974, 0.7656678098719567, 0.14348889188840985, 0.3010208271443844, 0.49753992492333055, 0.2347308264579624, 0.399606580613181, 0.7062801201827824, 0.08411125931888819, 0.3595561401452869);
      yield return Vec("hello world", 0.26985269505530596, 0.22693960461765528, 0.14113971241749823, 0.24302150262519717, 0.32151872501708567, 0.3751434606965631, 0.1993844413664192, 0.2747064249124378, 0.23551800823770463, 0.046951870899647474);
    }

    private static object[] Vec(string seed, params double[] draws) => new object[] { seed, draws };

    [Theory]
    [MemberData(nameof(ReferenceVectors))]
    public void MatchesReferenceSequence(string seed, double[] expected)
    {
      var rng = new MulberryRng(seed);
      for (int i = 0; i < expected.Length; i++)
        Assert.Equal(expected[i], rng.NextDouble());
    }

    [Fact]
    public void DrawsAreInUnitInterval()
    {
      var rng = new MulberryRng("seed");
      for (int i = 0; i < 1000; i++)
      {
        double d = rng.NextDouble();
        Assert.True(d >= 0.0 && d < 1.0, $"draw {d} out of [0,1)");
      }
    }

    [Fact]
    public void SeedIterCountsDraws()
    {
      var rng = new MulberryRng("x");
      Assert.Equal(0, rng.SeedIter);
      rng.NextDouble();
      rng.NextDouble();
      rng.NextDouble();
      Assert.Equal(3, rng.SeedIter);
    }

    [Fact]
    public void SameSeedSameSequence()
    {
      var a = new MulberryRng("repeat");
      var b = new MulberryRng("repeat");
      for (int i = 0; i < 20; i++) Assert.Equal(a.NextDouble(), b.NextDouble());
    }

    [Fact]
    public void RestoreFromSeedIterEqualsReplay()
    {
      // Drawing N then continuing must equal seeding fresh at (seed, N): the O(1)
      // restore the save/undo model relies on (no replay).
      var live = new MulberryRng("save", 0);
      for (int i = 0; i < 5; i++) live.NextDouble();
      Assert.Equal(5, live.SeedIter);

      var restored = new MulberryRng("save", 5);
      Assert.Equal(5, restored.SeedIter);
      for (int i = 0; i < 10; i++)
        Assert.Equal(live.NextDouble(), restored.NextDouble());
    }

    [Fact]
    public void SetSeedResetsState()
    {
      var rng = new MulberryRng("a");
      rng.NextDouble();
      rng.NextDouble();
      rng.SetSeed("a", 0);
      Assert.Equal(0, rng.SeedIter);
      Assert.Equal("a", rng.Seed);
      var fresh = new MulberryRng("a");
      Assert.Equal(fresh.NextDouble(), rng.NextDouble());
    }

    [Fact]
    public void IntSeedMapsToInvariantDecimalString()
    {
      // new MulberryRng(42) draws the same stream as the string seed "42".
      var fromInt = new MulberryRng(42);
      var fromStr = new MulberryRng("42");
      Assert.Equal("42", fromInt.Seed);
      for (int i = 0; i < 10; i++) Assert.Equal(fromStr.NextDouble(), fromInt.NextDouble());
    }

    [Fact]
    public void NullSeedTreatedAsEmpty()
    {
      var rng = new MulberryRng((string)null);
      Assert.Equal(string.Empty, rng.Seed);
      var empty = new MulberryRng("");
      Assert.Equal(empty.NextDouble(), rng.NextDouble());
    }
  }
}
